# Site settings
title: Maryanns Portfolio
author:
  name: Maryann Agofure
  email: maryannagofure@gmail.com
description: "Personal website"

# Build settings
remote_theme: jekyll/minima

header_pages:
  - index.md
  - work.html
  - contact.html